application: my-app
version: 1
runtime: python
api_version: 1

handlers:

- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /static/(.*)
  static_files: static/\1
  upload: static/.*

- url: /.*
  script: main.py
